//
// Created by Jasper on 1/22/2024.
//

#ifndef NEBULA_MAIN_TEXTURETYPE_HPP
#define NEBULA_MAIN_TEXTURETYPE_HPP

enum class TextureType {
    ALBEDO,
    NORMAL,
    ROUGHNESS,
    METALLIC,
    METALLICROUGHNESS,
    COUNT
};

#endif //NEBULA_MAIN_TEXTURETYPE_HPP
